name: branch-build
on:
  push:
    branches-ignore:
      - dev
      - master
      - 'version-increment-*'
jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.BRANCH_BUILD_ENABLED }} == 'true' ]; then
            echo "::set-output name=ok::enabled"
          fi
  compile-codebase:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: restore lerna
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            package-lock.json
          key: ${{ runner.os }}-branch-build-${{ hashFiles('**/package.json') }}
      - run: npm install --production=false --loglevel notice --legacy-peer-deps
      - run: npm run lint
      - run: npm run test:packages
      - run: npm run build-client
