name: update-deps-branch
on:
  push:
    branches:
      [dev]
jobs:
  secrets-gate:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check-secrets.outputs.ok }}
    steps:
      - name: check for secrets needed to run workflows
        id: check-secrets
        run: |
          if [ ${{ secrets.UPDATE_DEPS_BRANCH_ENABLED }} == 'true' ]; then
            echo "::set-output name=ok::enabled"
          fi
  update-deps-branch:
    needs:
      - secrets-gate
    if: ${{ needs.secrets-gate.outputs.ok == 'enabled' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Merge dev into deps branch
        uses: devmasx/merge-branch@1.4.0
        with:
          label_name: 'merged dev into deps'
          from_branch: 'dev'
          target_branch: 'deps'
          github_token: ${{ github.token }}